Squashed 5 commits from 2023-02-02
- make sure promtail is gone (#1893)
- fix script
- forget to fix the main issue
- Distributed rmb (#1892)
- don't return an error if loading of config fails

diff --git a/bins/packages/vector/files/zinit-vector.yaml b/bins/packages/vector/files/zinit-vector.yaml
--- a/bins/packages/vector/files/zinit-vector.yaml
+++ b/bins/packages/vector/files/zinit-vector.yaml
@@ -2,11 +2,29 @@
 # in its own process group
 exec: |
   sh -c '
-  pkill vector
+  set -e
+
+  pkill vector || true
 
   export NODE=$(identityd -address)
   export FARM=$(identityd -farm)
   export NETWORK=$(identityd -net)
+
+  if [ "${NODE}" = "" ]; then
+    echo "cannot get node id"
+    exit 1
+  fi
+
+  if [ "${FARM}" = "" ]; then
+    echo "cannot get farm id"
+    exit 1
+  fi
+
+  if [ "${NETWORK}" = "" ]; then
+    echo "cannot get farm id"
+    exit 1
+  fi
+
   exec vector -c /etc/vector/vector.yaml
   '
 log: stdout
